version: "3"

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: pinterest-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysqldb
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: pinterest-php
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel

  mysqldb:
    image: mysql:5.7.29
    container_name: pinterest-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel

  myadmin:
    image: phpmyadmin/phpmyadmin:4.8.1
    container_name: pinterest-phpmyadmin
    ports:
      - "8081:80"
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysqldb
      PMA_ARBITRARY: 1
    links:
      - mysqldb
    depends_on:
      - mysqldb
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: pinterest-composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: ["composer", "--ignore-platform-reqs"]

  npm:
    image: node:13.7
    container_name: pinterest-npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: pinterest-artisan
    volumes:
      - ./src:/var/www/html:delegated
    working_dir: /var/www/html
    links:
      - composer
    depends_on:
      - composer
    user: laravel
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel
